from rapidfuzz import fuzz

#atp i shd just call em Syns ... FAH!

PossibleImportantSynonyms = {
    "syllabus": [
        "syllabus",
        "detailed syllabus",
        "course syllabus",
        "course content",
        "course contents",
        "contents",
        "modules",
        "module",
        "units",
        "unit",
        "topics",
        "course topics",
        "topics covered",
        "curriculum",
        "course curriculum",
        "curricular content",
        "course structure",
        "course outline",
        "outline",
        "subject outline",
        "teaching plan",
        "learning plan",
        "scheme of studies",
        "scheme of instruction",
        "scheme of examination",
        "academic content",
        "instructional content",
        "lecture plan",
        "lecture schedule",
        "module details",
        "unit details",
        "unit-wise content",
        "unit-wise distribution",
        "unit-wise syllabus",
        "chapter distribution",
        "chapter-wise distribution",
        "chapter-wise syllabus",
        "topics and subtopics",
        "detailed contents",
        "paper contents",
        "paper structure",
        "course details",
        "subject matter",
        "body of knowledge",
        "learning units",
        "areas of study",
        "course material",
        "academic syllabus",
        "prescribed syllabus",
        "syllabi",
        "module-wise syllabus",
        "module-wise contents",
        "unit plan",
        "course framework",
        "curriculum framework",
        "content outline",
        "course organization",
        "course organisation",
    ],

    "books": [
        "books",
        "text book",
        "text books",
        "textbook",
        "textbooks",
        "recommended books",
        "recommended readings",
        "suggested books",
        "suggested readings",
        "readings",
        "references",
        "reference",
        "reference books",
        "bibliography",
        "reading list",
        "recommended bibliography",
        "additional readings",
        "further readings",
        "further reading",
        "supplementary readings",
        "supplementary books",
        "suggested references",
        "recommended references",
        "learning resources",
        "study materials",
        "study material",
        "course resources",
        "resource materials",
        "resource books",
        "prescribed books",
        "prescribed texts",
        "prescribed readings",
        "essential readings",
        "essential books",
        "core readings",
        "core texts",
        "primary references",
        "secondary references",
        "recommended literature",
        "reference material",
        "reference materials",
        "books and references",
        "texts and references",
        "learning references",
        "supporting resources",
        "additional resources",
        "source materials",
    ],

    "course_outcome": [
        "course outcome",
        "course outcomes",
        "outcomes",
        "learning outcomes",
        "course learning outcomes",
        "expected outcomes",
        "expected learning outcomes",
        "programme outcomes",
        "program outcomes",
        "programme specific outcomes",
        "program specific outcomes",
        "programme educational objectives",
        "program educational objectives",
        "peo",
        "po",
        "pso",
        "co",
        "course objectives",
        "objectives",
        "learning objectives",
        "instructional objectives",
        "aims and objectives",
        "goals",
        "course goals",
        "educational goals",
        "competencies",
        "skills acquired",
        "skills developed",
        "knowledge gained",
        "student learning outcomes",
        "graduate attributes",
        "attainment targets",
        "intended outcomes",
        "intended learning outcomes",
        "expected competencies",
        "target competencies",
        "learning achievements",
        "course attainments",
        "outcome assessment",
        "course endpoint",
        "what students will learn",
        "student outcomes",
    ],

    "overview": [
        "overview",
        "course overview",
        "course description",
        "description",
        "subject description",
        "paper description",
        "programme description",
        "program description",
        "introduction",
        "course introduction",
        "subject introduction",
        "about the course",
        "about this course",
        "course summary",
        "summary",
        "abstract",
        "preface",
        "background",
        "rationale",
        "need for the course",
        "course rationale",
        "aim",
        "aims",
        "objectives",
        "course objectives",
        "purpose",
        "scope",
        "scope of the course",
        "brief description",
        "general description",
        "overview of the course",
        "course profile",
        "paper profile",
        "subject profile",
        "course information",
        "course details",
        "general information",
        "intended audience",
        "course context",
        "module overview",
        "course synopsis",
        "synopsis",
        "executive summary",
        "learning context",
    ],
}

def Find_headers(layout_blocks):

    headers = []

    for block in layout_blocks:
        text = block["text"].strip()

        for actual_word, synonyms in PossibleImportantSynonyms.items():
            for synonym in synonyms: 
                score = fuzz.partial_ratio(synonym.lower(), text.lower())

                if score >= 85: 
                    headers.append({
                        "actual_word": actual_word,
                        "text": text,
                        "page": block["page"],
                        "confidence": score/100
                    })

    return headers